[book]
authors = []
language = "es"
multilingual = true
src = "src"
[preprocessor.katex]
block-delimiter = { left = "[$%", right = "%$]" }
inline-delimiter = { left = "($%", right = "$%)" }
pre-render = true